Repository eclipse-uprotocol/up-spec, pull requests merged in 2024-05, with the labels that each got.

#126 Simplification of UUri Data model
  up-core-api/uprotocol/uri.proto
Labels: enhancement

#133 Remove the CallOptions message
  up-core-api/uprotocol/uattributes.proto
Labels: enhancement

#121 Make UUri specification more formal
  README.adoc
  basics/uri.adoc
  basics/uri.drawio.svg
  up-core-api/pom.xml
Labels: documentation, enhancement, v1.5.8

#135 Update MQTT 5 uTransport specification
  up-l1/mqtt.adoc
  up-l1/mqtt_5.adoc
Labels: v1.5.8

#155 Move UUri invariants to UAttributes specification
  basics/uattributes.adoc
  basics/uri.adoc
Labels: bug, v1.5.8

#154 Update error_model.adoc
  basics/error_model.adoc
Labels: bug, v1.5.8

#151 Messaging Pattern API Specifications
  up-l2/README.adoc
  up-l2/api.adoc
  up-l2/rpcclient.adoc
Labels: documentation, enhancement, v1.5.8

#156 Align uri.proto with spec
  up-core-api/uprotocol/v1/uri.proto
Labels: documentation, enhancement, v1.5.8

#149 Updated uTwin doc to match uTwin proto file
  up-l3/utwin/v2/README.adoc
Labels: documentation, v1.5.8

#103 Conform Zenoh spec to 1.5.8
  up-l1/zenoh.adoc
Labels: documentation, enhancement, v1.5.8

#158 Add RPC response message usage definition
  basics/error_model.adoc
Labels: documentation

#166 Remove obsolete proto imports
  up-core-api/uprotocol/core/udiscovery/v3/udiscovery.proto
  up-core-api/uprotocol/core/usubscription/v3/usubscription.proto
Labels: bug

#167 Restrict authority to lowercase unreserved characters only
  basics/uri.adoc
Labels: enhancement
