Repository eclipse-uprotocol/up-spec, pull requests merged in 2024-08, with the labels that each got.

#215 Clarification for populating comstatus for RPC request failure
  basics/error_model.adoc
Labels: documentation, enhancement

#230 Change OFT spec item revision
  basics/uri.adoc
Labels: bug

#231 Fix typo
  languages.adoc
Labels: bug, documentation
