Repository eclipse-uprotocol/up-spec, pull requests merged in 2024-11, with the labels that each got.

#241 Mark up CloudEvent requirements as OFT spec items
  up-l1/README.adoc
  up-l1/cloudevents.adoc
Labels: documentation

#247 Remove ambiguity for UNSPECIFIED UPayloadFormat
  basics/upayloadformat.adoc
  up-core-api/uprotocol/v1/uattributes.proto
Labels: breaking change

#246 Add Initial name & number Registry Requirements
  up-core-api/uprotocol/core/ustreamer/v1/ustreamer.proto
  up-core-api/uprotocol/core/utwin/v2/utwin.proto
  up-l3/README.adoc
Labels: enhancement

#238 First rewrite of the uSubscription spec
  up-l3/usubscription/v3/README.adoc
  up-l3/usubscription/v3/local_subscribe.puml
  up-l3/usubscription/v3/local_subscribe.svg
  up-l3/usubscription/v3/remote_subscription.puml
  up-l3/usubscription/v3/remote_subscription.svg
  up-l3/usubscription/v3/subscription_sm.drawio.svg
  up-l3/usubscription/v3/unsub_local.puml
  up-l3/usubscription/v3/unsub_local.svg
  up-l3/usubscription/v3/unsub_remote.puml
  up-l3/usubscription/v3/unsub_remote.svg
Labels: documentation
