Repository eclipse-uprotocol/up-spec, pull requests merged in 2025-06, with the labels that each got.

#282 Remove duplicate requirement
  up-l3/usubscription/v3/README.adoc
Labels: documentation

#284 Fix typo in requirement ID that breaks oft runs
  up-l3/udiscovery/v3/service.adoc
Labels: bug

#283 Remove subscriber/subscription list pagination
  up-core-api/uprotocol/core/usubscription/v3/usubscription.proto
  up-l3/usubscription/v3/README.adoc
Labels: breaking change

#287 Cover UTransport requirements by default
  up-l1/README.adoc
  up-l1/mqtt_5.adoc
  up-l1/zenoh.adoc
Labels: enhancement

#290 Consistent uEntity naming
  README.adoc
  basics/namespace.adoc
  basics/permissions.adoc
  basics/uattributes.adoc
  basics/versioning.adoc
  pom.xml
  principles.adoc
  terms.adoc
  up-core-api/uprotocol/core/README.adoc
  up-core-api/uprotocol/core/udiscovery/v3/udiscovery.proto
  up-core-api/uprotocol/core/udiscovery/v3/udiscovery_replicator.proto
  up-core-api/uprotocol/core/usubscription/v3/usubscription.proto
  up-core-api/uprotocol/core/utwin/v2/utwin.proto
  up-core-api/uprotocol/uoptions.proto
  up-core-api/uprotocol/v1/ucode.proto
  up-core-api/uprotocol/v1/umessage.proto
  up-l1/README.adoc
  up-l1/cloudevents.adoc
  up-l1/mqtt_5.adoc
  up-l1/someip.adoc
  up-l2/dispatchers/README.adoc
  up-l3/README.adoc
  up-l3/udiscovery/v3/README.adoc
  up-l3/udiscovery/v3/client.adoc
  up-l3/udiscovery/v3/service.adoc
  up-l3/usubscription/v3/README.adoc
  up-l3/utwin/v2/README.adoc
Labels: documentation
