Repository eclipse-uprotocol/up-spec, pull requests merged in 2025-02, with the labels that each got.

#260 Add OFT specitem definitions
  up-l1/zenoh.adoc
Labels: documentation

#261 Visually highlight requirements
  up-l3/usubscription/v3/README.adoc
Labels: enhancement

#263 Fix requirements for preventing sender address spoofing
  up-l1/README.adoc
Labels: bug
