Repository eclipse-uprotocol/up-spec, pull requests merged in 2025-07, with the labels that each got.

#293 Fix covered OFT specitem ID
  basics/uuid_string_serialization.feature
Labels: bug

#295 Fix copy-paste duplication of req id
  up-l3/usubscription/v3/README.adoc
Labels: bug, documentation

#296 Add test-required attribute to some requirements
  up-l3/usubscription/v3/README.adoc
Labels: enhancement

#299 Add missing utest attribute for reset-protobuf requirement
  up-l3/usubscription/v3/README.adoc
Labels: enhancement
